---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auditar-plano
  labels:
    app: auditar-plano
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auditar-plano
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: auditar-plano
    spec:
      containers:
        - name: auditar-plano
          image: us-central1-docker.pkg.dev/no-mono/app-nativas-uniandes/auditar-plano:5.0
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "60m"
          ports:
            - containerPort: 5003
          imagePullPolicy: Always
          env:
            - name: "DB_URL"
              valueFrom:
                secretKeyRef:
                  name: app-mono-secrects
                  key: DB_URL
            - name: "PULSAR_HOST"
              valueFrom:
                secretKeyRef:
                  name: app-mono-secrects
                  key: PULSAR_HOST
#### AUDITAR PLANO BACK SERVICE
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: auditar-plano-config
spec:
  healthCheck:
    checkIntervalSec: 30
    port: 5003
    type: HTTP
    requestPath: /health
### AUDITAR PLANO SERVICE
---
kind: Service
apiVersion: v1
metadata:
  name: servicio-auditar-plano
  annotations:
    cloud.google.com/backend-config: '{"default": "auditar-plano-config"}'
spec:
  type: NodePort
  selector:
    app: auditar-plano
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5003
      nodePort: 31003

#####
########
####
#### AUDITORIA SERVICES
## DEPLOYMENT
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auditoria
  labels:
    app: auditoria
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auditoria
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: auditoria
    spec:
      containers:
        - name: auditoria
          image: us-central1-docker.pkg.dev/no-mono/app-nativas-uniandes/auditoria:2.0
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "60m"
          ports:
            - containerPort: 5001
          imagePullPolicy: Always
          env:
            - name: "DB_URL"
              valueFrom:
                secretKeyRef:
                  name: app-mono-secrects
                  key: DB_URL
            - name: "PULSAR_HOST"
              valueFrom:
                secretKeyRef:
                  name: app-mono-secrects
                  key: PULSAR_HOST

#### AUDITARia PLANO BACK SERVICE
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: auditoria-config
spec:
  healthCheck:
    checkIntervalSec: 30
    port: 5001
    type: HTTP
    requestPath: /health
### AUDITARIA PLANO SERVICE
---
kind: Service
apiVersion: v1
metadata:
  name: servicio-auditoria
  annotations:
    cloud.google.com/backend-config: '{"default": "auditoria-config"}'
spec:
  type: NodePort
  selector:
    app: auditoria
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
      nodePort: 31001

#####
########
####
#### PROPIEDADAES
## DEPLOYMENT
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: propiedades
  labels:
    app: propiedades
spec:
  replicas: 2
  selector:
    matchLabels:
      app: propiedades
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: propiedades
    spec:
      containers:
        - name: propiedades
          image: us-central1-docker.pkg.dev/no-mono/app-nativas-uniandes/propiedades:5.0
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "60m"
          ports:
            - containerPort: 5002
          imagePullPolicy: Always
          env:
            - name: "DB_URL"
              valueFrom:
                secretKeyRef:
                  name: app-mono-secrects
                  key: DB_URL
            - name: "PULSAR_HOST"
              valueFrom:
                secretKeyRef:
                  name: app-mono-secrects
                  key: PULSAR_HOST

#### AUDITARia PLANO BACK SERVICE
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: propiedades-config
spec:
  healthCheck:
    checkIntervalSec: 30
    port: 5002
    type: HTTP
    requestPath: /health
### AUDITARIA PLANO SERVICE
---
kind: Service
apiVersion: v1
metadata:
  name: servicio-propiedades
  annotations:
    cloud.google.com/backend-config: '{"default": "propiedades-config"}'
spec:
  type: NodePort
  selector:
    app: propiedades
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5002
      nodePort: 31002

#####
########
####
#### PLANOS
## DEPLOYMENT
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: planos
  labels:
    app: planos
spec:
  replicas: 2
  selector:
    matchLabels:
      app: planos
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: planos
    spec:
      containers:
        - name: planos
          image: us-central1-docker.pkg.dev/no-mono/app-nativas-uniandes/planos:5.0
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "60m"
          ports:
            - containerPort: 5000
          imagePullPolicy: Always
          env:
            - name: "DB_URL"
              valueFrom:
                secretKeyRef:
                  name: app-mono-secrects
                  key: DB_URL
            - name: "PULSAR_HOST"
              valueFrom:
                secretKeyRef:
                  name: app-mono-secrects
                  key: PULSAR_HOST

#### AUDITARia PLANO BACK SERVICE
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: planos-config
spec:
  healthCheck:
    checkIntervalSec: 30
    port: 5000
    type: HTTP
    requestPath: /health
### AUDITARIA PLANO SERVICE
---
kind: Service
apiVersion: v1
metadata:
  name: servicio-planos
  annotations:
    cloud.google.com/backend-config: '{"default": "planos-config"}'
spec:
  type: NodePort
  selector:
    app: planos
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 31000
