apiVersion: v1
stringData:
  DB_URL: "postgresql://user:password@172.23.0.2:5432/postgres"
kind: Secret
metadata:
  name: app-mono-secrects
---
apiVersion: v1
stringData:
  PULSAR_URL: "postgres"
kind: Secret
metadata:
  name: app-mono-secrects
---

